wandb_version: 1

dataset:
  desc: null
  value: StackOverflow
plm_model:
  desc: null
  value: all-mpnet-base-v2
model:
  desc: null
  value: ZTM
num_topics:
  desc: null
  value: 50
num_groups:
  desc: null
  value: 20
dropout:
  desc: null
  value: 0.2
hidden_dim_1:
  desc: null
  value: 384
hidden_dim_2:
  desc: null
  value: 384
theta_temp:
  desc: null
  value: 1.0
DT_alpha:
  desc: null
  value: 3.0
TW_alpha:
  desc: null
  value: 2.0
weight_GR:
  desc: null
  value: 1.0
alpha_GR:
  desc: null
  value: 5.0
weight_InfoNCE:
  desc: null
  value: 50.0
beta_temp:
  desc: null
  value: 0.2
weight_ECR:
  desc: null
  value: 100.0
use_pretrainWE:
  desc: null
  value: true
wandb_prj:
  desc: null
  value: topmost
epochs:
  desc: null
  value: 500
batch_size:
  desc: null
  value: 200
lr:
  desc: null
  value: 0.002
device:
  desc: null
  value: cpu
seed:
  desc: null
  value: 0
lr_scheduler:
  desc: null
  value: StepLR
lr_step_size:
  desc: null
  value: 125
tune_SVM:
  desc: null
  value: false
glove:
  desc: null
  value: glove.6B.100d.txt
wete_beta:
  desc: null
  value: 0.5
wete_epsilon:
  desc: null
  value: 0.1
init_alpha:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1758383069.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      3:
      - 16
      - 23
      4: 3.10.18
      5: 0.16.6
      6: 4.30.2
      8:
      - 4
      - 5
      13: darwin-arm64
